Inital work towards supporting Azure RTOS
nanoframework/nf-interpreter pull request #1711
Opened 2020-10-02 17:50 UTC by networkfusion

Uses the STM32L4 target as a starting point and using https://github.com/azure-rtos/getting-started/blob/master/STMicroelectronics/STM32L4_L4%2B/ as a guide.

## Description
This will unlock the possibility of using Azure RTOS (threadx) on nanoFramework

## Motivation and Context
Improvement

## How Has This Been Tested?
none yet as it still does not build

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-02 17:50 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1711) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1711) before we can accept your contribution.<br/><br/>:x: networkfusion [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1711)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-interpreter?pullRequest=1711) it.</sub>

2020-10-03 08:56 UTC, josesimoes requested changes
I stopped my review on the board name thing. 
Would like to reach an agreement on that before going deeper.

2020-10-03 08:56 UTC, josesimoes commented on CMakeLists.txt
> +#######################
As we are now down this path, we should follow the simplified approach of "just" adding the platform subdirectory and the rest of the cmake script should live there.

2020-10-03 08:56 UTC, josesimoes commented on CMake/AzureRTOS.CMakeLists.cmake.in
> +    GIT_TAG ${AZURERTOS_VERSION_TAG}  # target specified branch
this will have to be RTOS_TAG

2020-10-03 08:56 UTC, josesimoes commented on targets/AzureRTOS/STM32L4_L4+/CMakeLists.txt
> +#
The path pattern we've been following is PLATFORM\TARGET_BOARD.
On some exception (like FreeRTOS) we have an intermediate one for the silicon vendor.
Unless there is a very good reason we should follow it here. This has to be the target name, something like `ST_B-L475E-IOT01A`

(note that Azure RTOS supports two similar boards B-L475E-IOT01A (with L4 series) and B-L475I-IOT01A (with L4+ series, more flash, more RAM)

I say that we should target the minimum viable product (the L4). The other one can be added to community targets, just like we've been doing in similar situations.

2020-10-03 08:58 UTC, josesimoes commented on CMake/Modules/FindAzureRTOS.cmake
> +set(AZURERTOS_SUPPORTED_SERIES STM32L4_L4+ CACHE INTERNAL "supported series names for AzureRTOS")
Could be me, but I don't have a good feeling on using '+' on a name like this... it smells and I sense a disturbance on the force with potential problems ahead... 😉

2020-10-03 11:21 UTC, piwi1263 commented on CMake/Modules/FindAzureRTOS.cmake
> +set(AZURERTOS_SUPPORTED_SERIES STM32L4_L4+ CACHE INTERNAL "supported series names for AzureRTOS")
@josesimoes Change to L4P ?

2020-10-03 14:37 UTC, piwi1263 commented on CMake/Modules/FindAzureRTOS.cmake
> +set(AZURERTOS_SUPPORTED_SERIES STM32L4_L4+ CACHE INTERNAL "supported series names for AzureRTOS")
Found on st.com 
![image](https://user-images.githubusercontent.com/10466039/94994167-38bbd800-0596-11eb-8bf6-a346213ea93c.png)

So I reckon we can follow along those lines as well and change that STM32L4_L4+ into STM32L4 and when that + is coming we can, depending on the line used, add f.e. STM32L4P5 or STML4Q5 etc.

2020-10-03 15:28 UTC, josesimoes commented on CMake/Modules/FindAzureRTOS.cmake
> +set(AZURERTOS_SUPPORTED_SERIES STM32L4_L4+ CACHE INTERNAL "supported series names for AzureRTOS")
L4P sounds ok

2020-10-03 19:14 UTC, piwi1263 commented on CMake/Modules/FindAzureRTOS.cmake
> +set(AZURERTOS_SUPPORTED_SERIES STM32L4_L4+ CACHE INTERNAL "supported series names for AzureRTOS")
It is more in the sence of STM32L4xx STM32L4P5xx STM32L4R9xx etc.

Maybe ST is better off with STM32L4nn and STM32L4an where a = alfabetic and n = numeric instead of x = everything. But I reckon that is too much of change.

2020-10-05 10:31 UTC, merged