Set proper timeout when sending/receiving data through network
nanoframework/nf-interpreter pull request #1753
Opened 2020-10-29 12:55 UTC by MateuszKlatecki

## Description

Set proper timeout value 

## Motivation and Context

- Fixes nanoFramework/Home/issues/656

## How Has This Been Tested?

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-10-29 12:55 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1753) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1753) before we can accept your contribution.<br/><br/>:x: MateuszKlatecki [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1753)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-interpreter?pullRequest=1753) it.</sub>

2020-10-30 01:44 UTC, josesimoes requested changes

2020-10-30 01:44 UTC, josesimoes commented on src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
> +    CLR_INT64 sendRecvTimeout = stack.Arg5().NumericByRef().s4;
Let's call this just `timeout`, for simplicity.

2020-10-30 01:44 UTC, josesimoes commented on src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
> +        hbTimeout.SetInteger(sendRecvTimeout * TIME_CONVERSION__TO_MILLISECONDS);
It's OK to call this one directly. No need to check for == -1.
The C# guarantees that this will be either -1 or whatever the user has set it.
When setting the value for the timer this is properly checked so no worries here.

2020-10-30 07:21 UTC, MateuszKlatecki commented on src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
> +    CLR_INT64 sendRecvTimeout = stack.Arg5().NumericByRef().s4;
The timeout variable is already declared in this function to something else.
Since the condition below is not needed, as you can see, this value is only used once, so I won't create a temporary variable.

2020-10-30 07:21 UTC, MateuszKlatecki commented on src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
> +        hbTimeout.SetInteger(sendRecvTimeout * TIME_CONVERSION__TO_MILLISECONDS);
You rightly noticed. In CLR_RT_ExecutionEngine :: InitTimeout there is already logic that will take care of the correct value.

2020-10-30 09:01 UTC, josesimoes commented on src/DeviceInterfaces/System.Net/sys_net_native_System_Net_Sockets_NativeSocket.cpp
> +    CLR_INT64 sendRecvTimeout = stack.Arg5().NumericByRef().s4;
That's OK too. That's used mostly for debugging purposes. When building with optimisations the compiler would do that anyway.

2020-10-30 09:01 UTC, merged