ToString() reimplementation
nanoframework/nf-interpreter pull request #1843
Opened 2021-02-28 15:37 UTC by SandorDobos

Numeric ToString() related managed code parts moved from lib-CoreLibrary to native code in nf-interpreter.

## Description
Logic in native code reimplemented.
Some deviances from official ToString() behaviour fixed, like rounding, digit count, e+x format, etc.
This PR has a related PR in lib-CoreLibrary repo!

## Motivation and Context

- Fixes nanoFramework/Home#679 and various other formatting deviances not yet reported at all.

## How Has This Been Tested?

          I create an nf project in VS and added the following class to it:

          public static class ToStringAsserts
          {
              public static void Run()
              {
                  //AssertToConsole("(123.456).ToString(\"C\"))","",(123.456).ToString("C"));
                  //AssertToConsole("(-123.456).ToString(\"C\"))","",(-123.456).ToString("C"));
                  //AssertToConsole("(123.456).ToString(\"C3\"))","",(123.456).ToString("C3"));
                  //AssertToConsole("(-123.456).ToString(\"C3\"))","",(-123.456).ToString("C3"));
                  AssertToConsole("(1).ToString(\"Da1x\")", "Da1x", (1).ToString("Da1x"));
                  AssertToConsole("(1).ToString(\"D\")", "1", (1).ToString("D"));
                  AssertToConsole("(-1).ToString(\"D\")", "-1", (-1).ToString("D"));
                  AssertToConsole("(1234).ToString(\"D\")", "1234", (1234).ToString("D"));
                  AssertToConsole("(-1234).ToString(\"D\")", "-1234", (-1234).ToString("D"));
                  AssertToConsole("(1234).ToString(\"D6\")", "001234", (1234).ToString("D6"));
                  AssertToConsole("(-1234).ToString(\"D6\")", "-001234", (-1234).ToString("D6"));
                  AssertToConsole("(Int32.MaxValue).ToString(\"D\")", "2147483647", (Int32.MaxValue).ToString("D"));
                  AssertToConsole("(Int32.MinValue).ToString(\"D\")", "-2147483648", (Int32.MinValue).ToString("D"));
                  AssertToConsole("(Int32.MaxValue).ToString(\"D21\")", "000000000002147483647",
          (Int32.MaxValue).ToString("D21")); AssertToConsole("(Int32.MinValue).ToString(\"D21\")",
          "-000000000002147483648", (Int32.MinValue).ToString("D21"));
                  AssertToConsole("(Int64.MaxValue).ToString(\"D\")", "9223372036854775807",
          (Int64.MaxValue).ToString("D")); AssertToConsole("(Int64.MinValue).ToString(\"D\")", "-9223372036854775808",
          (Int64.MinValue).ToString("D")); AssertToConsole("(Int64.MaxValue).ToString(\"D21\")",
          "009223372036854775807", (Int64.MaxValue).ToString("D21"));
                  AssertToConsole("(Int64.MinValue).ToString(\"D21\")", "-009223372036854775808",
          (Int64.MinValue).ToString("D21")); AssertToConsole("(Int32.MaxValue+100).ToString(\"D\")", "2147483747",
          ((Int64)Int32.MaxValue + 100).ToString("D")); AssertToConsole("(Int32.MinValue-100).ToString(\"D\")",
          "-2147483748", ((Int64)Int32.MinValue - 100).ToString("D"));
                  AssertToConsole("(Int32.MaxValue+100).ToString(\"D21\")", "000000000002147483747",
          ((Int64)Int32.MaxValue + 100).ToString("D21")); AssertToConsole("(Int32.MinValue-100).ToString(\"D21\")",
          "-000000000002147483748", ((Int64)Int32.MinValue - 100).ToString("D21"));
                  //AssertToConsole("(1052.0329112756).ToString(\"E\"))","",(1052.0329112756).ToString("E"));
                  //AssertToConsole("(-1052.0329112756).ToString(\"E\"))","",(-1052.0329112756).ToString("E"));
                  //AssertToConsole("(1052.0329112756).ToString(\"E2\"))","",(1052.0329112756).ToString("E2"));
                  //AssertToConsole("(-1052.0329112756).ToString(\"E2\"))","",(-1052.0329112756).ToString("E2"));
                  //AssertToConsole("(1052.0329112756).ToString(\"e\"))","",(1052.0329112756).ToString("e"));
                  //AssertToConsole("(-1052.0329112756).ToString(\"e\"))","",(-1052.0329112756).ToString("e"));
                  //AssertToConsole("(1052.0329112756).ToString(\"e2\"))","",(1052.0329112756).ToString("e2"));
                  //AssertToConsole("(-1052.0329112756).ToString(\"e2\"))","",(-1052.0329112756).ToString("e2"));
                  AssertToConsole("(1234.567).ToString(\"F\"))", "1234.57", (1234.567).ToString("F"));
                  AssertToConsole("(-1234.567).ToString(\"F\"))", "-1234.57", (-1234.567).ToString("F"));
                  AssertToConsole("(1234.567).ToString(\"F0\"))", "1235", (1234.567).ToString("F0"));
                  AssertToConsole("(-1234.567).ToString(\"F0\"))", "-1235", (-1234.567).ToString("F0"));
                  AssertToConsole("(1234).ToString(\"F1\"))", "1234.0", (1234).ToString("F1"));
                  AssertToConsole("(-1234).ToString(\"F1\"))", "-1234.0", (-1234).ToString("F1"));
                  AssertToConsole("(1234.56).ToString(\"F4\"))", "1234.5600", (1234.56).ToString("F4"));
                  AssertToConsole("(-1234.56).ToString(\"F4\"))", "-1234.5600", (-1234.56).ToString("F4"));
                  AssertToConsole("(1234.56).ToString(\"F1\"))", "1234.6", (1234.56).ToString("F1"));
                  AssertToConsole("(-1234.56).ToString(\"F1\"))", "-1234.6", (-1234.56).ToString("F1"));
                  AssertToConsole("(1234.0056).ToString(\"F1\"))", "1234.0", (1234.0056).ToString("F1"));
                  AssertToConsole("(-1234.0056).ToString(\"F1\"))", "-1234.0", (-1234.0056).ToString("F1"));
                  AssertToConsole("(1).ToString()", "1", (1).ToString());
                  AssertToConsole("(1).ToString(null)", "1", (1).ToString((string)null));
                  AssertToConsole("(1).ToString(String.Empty)", "1", (1).ToString(String.Empty));
                  AssertToConsole("(1234.567).ToString())", "1234.567", (1234.567).ToString());
                  AssertToConsole("(123.456).ToString(\"G\"))", "123.456", (123.456).ToString("G"));
                  AssertToConsole("(-123.456).ToString(\"G\"))", "-123.456", (-123.456).ToString("G"));
                  AssertToConsole("(123.4546).ToString(\"G2\"))", "1.2E+02", (123.4546).ToString("G2"));
                  AssertToConsole("(-123.4546).ToString(\"G2\"))", "-1.2E+02", (-123.4546).ToString("G2"));
                  AssertToConsole("(123.4546).ToString(\"G4\"))", "123.5", (123.4546).ToString("G4"));
                  AssertToConsole("(-123.4546).ToString(\"G4\"))", "-123.5", (-123.4546).ToString("G4"));
                  AssertToConsole("(123.4546).ToString(\"G10\"))", "123.4546", (123.4546).ToString("G10"));
                  AssertToConsole("(-123.4546).ToString(\"G10\"))", "-123.4546", (-123.4546).ToString("G10"));
                  AssertToConsole("(99.9999).ToString(\"G4\"))", "100", (99.9999).ToString("G4"));
                  AssertToConsole("(-99.9999).ToString(\"G4\"))", "-100", (-99.9999).ToString("G4"));
                  AssertToConsole("(1234567890).ToString(\"G\"))", "1234567890", (1234567890).ToString("G"));
                  AssertToConsole("(-1234567890).ToString(\"G\"))", "-1234567890", (-1234567890).ToString("G"));
                  AssertToConsole("(1234567890).ToString(\"G4\"))", "1.235E+09", (1234567890).ToString("G4"));
                  AssertToConsole("(-1234567890).ToString(\"G4\"))", "-1.235E+09", (-1234567890).ToString("G4"));
                  AssertToConsole("(9876543210).ToString(\"G4\"))", "9.877E+09", (9876543210).ToString("G4"));
                  AssertToConsole("(-9876543210).ToString(\"G4\"))", "-9.877E+09", (-9876543210).ToString("G4"));
                  AssertToConsole("(1234567890).ToString(\"G15\"))", "1234567890", (1234567890).ToString("G15"));
                  AssertToConsole("(-1234567890).ToString(\"G15\"))", "-1234567890", (-1234567890).ToString("G15"));
                  AssertToConsole("(1234.567).ToString(\"N\"))", "1,234.57", (1234.567).ToString("N"));
                  AssertToConsole("(-1234.567).ToString(\"N\"))", "-1,234.57", (-1234.567).ToString("N"));
                  AssertToConsole("(0).ToString(\"N0\"))", "0", (0).ToString("N0"));
 [...]

2021-03-01 08:47 UTC, josesimoes reviewed
Great work on this!! Congrats and thankyou. 👍🏻 💯

2021-03-01 08:48 UTC, josesimoes requested changes

2021-03-01 08:48 UTC, josesimoes commented on src/CLR/CorLib/corlib_native.cpp
>  #elif (NANOCLR_REFLECTION == FALSE)
Missing here the updated `method_lookup` and checksum for the build **without** reflection.
Can you please add that?

2021-03-01 08:49 UTC, josesimoes commented
@SandorDobos if you could squash all the commits into a single one, that would be great.

2021-03-01 22:10 UTC, SandorDobos commented on src/CLR/CorLib/corlib_native.cpp
>  #elif (NANOCLR_REFLECTION == FALSE)
Done!

2021-03-02 11:58 UTC, josesimoes approved these changes

2021-03-02 12:04 UTC, merged