WIP: System IO Directory class
nanoframework/nf-interpreter pull request #1883
Opened 2021-04-16 12:23 UTC by morali

## Description

Implement Directory API for System.IO.FileSystem

## Motivation and Context

This pull request implements Directory API for System.IO.FileSystem. 
For now it is very simple and i hope it could be used as a starter for expanding Directory API.
It will need changes to System.IO.FileSystem project. I will create pull request later.

## How Has This Been Tested?

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-04-21 16:28 UTC, josesimoes requested changes
Overall looking good. Just replace those exception throwers and we are good.

Nicely done! 👍🏻

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +    FAULT_ON_NULL(folderPath);
These should be `FAULT_ON_NULL_ARG` which will throw the ArgumentNull exception.
This one is for NullReference, which is not the intended exception.

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(filePathSrc);
same here

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(filePathDest);
same here

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(folderPath);
same here

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(folderPath);
same here

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(folderPath);
same here

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(folderPath);
same here

2021-04-21 16:28 UTC, josesimoes commented on src/System.IO.FileSystem/nf_sys_io_filesystem_System_IO_Directory.cpp
> +        FAULT_ON_NULL(folderPath);
same here

2021-04-22 06:20 UTC, morali commented
> 
> 
> Overall looking good. Just replace those exception throwers and we are good.
> 
> Nicely done! 👍🏻

Thank you, the exceptions throwers were replaced.

2021-04-22 11:24 UTC, josesimoes approved these changes
LGTM!

2021-04-22 11:26 UTC, merged