.net Core target for nanoCLR
nanoframework/nf-interpreter pull request #1976
Opened 2021-07-06 11:31 UTC by romanmashta

## Description

## Motivation and Context

- .net Core Native Host and CLI tools for hosting, running and debugging nanoCLR applications.

## How Has This Been Tested?

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-06 11:31 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1976) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1976) before we can accept your contribution.<br/><br/>:x: romanmashta [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1976)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-interpreter?pullRequest=1976) it.</sub>

2021-07-06 17:10 UTC, edleno2 commented
I'll pull this down today and give it a try.  I looked over the change - 66 files - not sure how much of that is duplicate with the win32 target that is already in place, maybe that's where that code came from?  So maybe the intention is to replace win32 target with this one?  Still having trouble wrapping my head around the use case - can this be used without changes to either Device Explorer or nanoFramewor.TestFramework - those are the only two "entry" points for connecting to a nanoCLR I think?

2021-07-06 17:18 UTC, romanmashta commented
>not sure how much of that is duplicate with the win32 target that is already in place, maybe that's where that code came from? 

You can see from this commit that I took the win32 code as it was. https://github.com/nanoframework/nf-interpreter/pull/1976/commits/cb33aaf74fcd5c8c01c84ddfed19ca593b0808c6
And made changes to those files which required. I think it worth probably to remove unchanged files from solution and just include them from win32 folder. It will make this target lighter. And will avoid duplication of code. At the moment I didnt know what files I will have to update. 

What do you think? Should I remove unchanged duplicates and include them from win32?

Thanks.

2021-07-06 17:52 UTC, edleno2 commented
> You can see from this commit that I took the win32 code as it was. [cb33aaf](https://github.com/nanoframework/nf-interpreter/commit/cb33aaf74fcd5c8c01c84ddfed19ca593b0808c6)

I didn't look at the individual commits - just the overall changes.  I've got it on my machine right now, but having some trouble getting all the parts to compile since I'm having to change to x64.  

I don't think it's a question of "how much to copy from win32" but whether to copy at all.  Should this be done using either a define or a runtime setting so that the new code is interspersed within the current win32 solution?  That's two approaches (do it at compile time, or do it at runtime).

An alternative is to plan on retiring the win32 target and we change the test framework to invoke the CLI component and not the current win32 nanoCLR.exe - I'll mention @josesimoes  and @Ellerbach to get their opinions.

I do see that the CLI takes a COM port as an argument, so that answers how we would integrate - you start the CLI project up in Visual Studio with debugger attached and then go to another instance of VS and run your NF project and select the COM port you put in the CLI command line.  Do I have that right?

2021-07-06 18:05 UTC, edleno2 commented
Have to leave for a while - but if we continue with the forked version of nanoCLR(win32) then I'll want to make a suggestion on the handling of the AdditionalInclude directories so we can build in both x86 and x64.  Even after fixing that I still am not getting a good build of the CPP parts, so have to look closer to see what I missed.

2021-07-06 18:11 UTC, romanmashta commented
> Have to leave for a while - but if we continue with the forked version of nanoCLR(win32) then I'll want to make a suggestion on the handling of the AdditionalInclude directories so we can build in both x86 and x64. Even after fixing that I still am not getting a good build of the CPP parts, so have to look closer to see what I missed.

All projects in solution have to be compiled for x86. Including .net ones. I was targeted x86 initially because the original win32 project was x86 only from the beginning. I will try to make it compile and work for x64 also.

2021-07-06 18:14 UTC, edleno2 commented
Yes, I did switch to x86 and all projects built then.  The original nanoCLR was "Any CPU" and I would have expected it to build as x64 on my development machine.  And I just glanced at the original nanoCLR and there weren't any additional includes in the project file, so we might want to look at why there are additional include in the new solution.  Additional Includes tend to be a problem because they can cause problems when developers lay their solutions out a bit differently on their machine.  Not sure that's the case here, but I avoid anything that can break on another developers machine.

2021-07-06 18:33 UTC, edleno2 commented
I kind of forgot that you converted nanoCLR from an application to a library, so that explains more of your need to clone code.  We just have to decide on what to do with the current test framework and then figure out where to take this from there.  If we change to have the test framework use the CLI then we will have to copy the CLI .exe and the necessary .dll's during the post build of any test solution.  Not the end of the world, just a necessary change if we decide to go that way and kill off the win32 target that we have today.

2021-07-06 22:52 UTC, josesimoes commented
@edleno2 @romanmashta let's continue this conversation on Discord, shall we? It's more productive than here... 😉

2021-07-12 11:26 UTC, josesimoes requested changes

2021-07-12 11:26 UTC, josesimoes commented on targets/netcore/nanoFramework.nanoCLR.Native/Various.cpp
> +    targetInfo->BooterVersion.usMajor = 0;
Same here: it's better to change it in the common various.cpp

2021-07-12 11:26 UTC, josesimoes commented on targets/netcore/nanoFramework.nanoCLR.CLI/Program.cs
> +                    if (o.Assemblies.Any())
As per the project code style, please use open/close brackets, even if there a single line of code.
(multiple places with this)

2021-07-17 07:50 UTC, Ellerbach reviewed
Few comments, all up, looks good! Impatient to test it!

2021-07-17 07:50 UTC, Ellerbach commented on targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHostBuilder.cs
> +    public class NanoClrHostBuilder
It's a great practice to document all public classes, there public methods and properties.
It helps maintaining the code.
Would be great if you can add. There are quite some. Leaving the comment here but it's valid for quite some classes.
Those classes will be extracted and placed in the static documentation website.

2021-07-17 07:50 UTC, Ellerbach commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/Channel.cs
> +                    Thread.Sleep(100);
Why 100 and not 50 or 10 of 300?
Would be perfect to add a comment so it will make it easy to maintain.

2021-07-17 07:50 UTC, Ellerbach commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/Common/ListeningPortBase.cs
> +        private const int WaitTimeout = 100;
Why 100 and not 50 or 10 of 300?
Would be perfect to add a comment so it will make it easy to maintain.

2021-07-17 07:50 UTC, Ellerbach commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/NamedPipe/NamedPipeListeningPort.cs
> +    public class NamedPipeServerPort : ListeningPortBase
Stupid question: I though we would get out of named pipe? So is this used somewhere else?

2021-07-17 07:50 UTC, Ellerbach commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/TcpIp/TcpIpListeningPort.cs
> +        public TcpIpListeningPort(int port)
Will there be a way to listen over a real network, not just locally? Maybe for later on?

2021-07-17 19:35 UTC, romanmashta commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/NamedPipe/NamedPipeListeningPort.cs
> +    public class NamedPipeServerPort : ListeningPortBase
This Pull Request was made before our call. I've tried to implement it also. Will remove it.

2021-07-17 19:38 UTC, romanmashta commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/TcpIp/TcpIpListeningPort.cs
> +        public TcpIpListeningPort(int port)
Sure, it can listen on any interface. I will change it to 0.0.0.0 as default and will add an extra parameter if user needs to specify exact IP to bind to.

2021-07-17 19:39 UTC, romanmashta commented on targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHostBuilder.cs
> +    public class NanoClrHostBuilder
Yes, I will try to add comments.

2021-07-17 22:49 UTC, romanmashta commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/Channel.cs
> +                    Thread.Sleep(100);
I've reimplemented Wire ports to use Async Receive and Transmit, so these loops are not required anymore.

2021-07-17 22:50 UTC, romanmashta commented on targets/netcore/nanoFramework.nanoCLR.Host/Port/Common/ListeningPortBase.cs
> +        private const int WaitTimeout = 100;
I've reimplemented Wire ports to use Async Receive and Transmit, so these loops are not required anymore.

2021-07-18 13:45 UTC, romanmashta commented on targets/netcore/nanoFramework.nanoCLR.Host/NanoClrHostBuilder.cs
> +    public class NanoClrHostBuilder
I've added documentation comments to public classes and methods

2021-07-19 06:04 UTC, Ellerbach approved these changes
Thanks! Looks very good to me!
Question: why is the vspt.vsptlic file empty?

2021-07-19 08:51 UTC, romanmashta commented
@Ellerbach 
> Question: why is the vspt.vsptlic file empty?

I had concerns if it is okay to put valid license file on Github. Need to get clarification from Jose on that. It could be possible to replace valid license file on npm release build for distribution, but I'm not sure if it is okay to share it on GitHub. Also, it is not a blocker for local builds and tests. Virtual com management will run in the trial 14 days mode when the license file is empty.

2021-08-10 07:20 UTC, josesimoes approved these changes

2021-08-10 07:20 UTC, merged