Add NF_FEATURE_TRACE_TO_STDIO directed to Serial - Draft
nanoframework/nf-interpreter pull request #2044
Opened 2021-09-14 22:14 UTC by doingnz

## Description
Define ```"NF_FEATURE_TRACE_TO_STDIO": "4"``` in cmake-variants.json to enable debug_printf / trace to stdio to be output on UART4 using Serial Driver with default baud rate, patrity, etc. 

If ```NF_FEATURE_TRACE_TO_STDIO``` is defined, CMake\binutils.common.cmake will define ```FEATURE_TRACE_TO_STDIO = ${NF_FEATURE_TRACE_TO_STDIO}```, ```STM32_SERIAL_USE_UART${NF_FEATURE_TRACE_TO_STDIO} = TRUE``` and ```SERIAL_DRIVER_STDIO = SD${NF_FEATURE_TRACE_TO_STDIO}```.  i.e. in the tested environment defined ```FEATURE_TRACE_TO_STDIO=4, STM32_SERIAL_USE_UART4=TRUE and SERIAL_DRIVER_STDIO=SD4```

Use ```#if define(FEATURE_TRACE_TO_STDIO)/#endif``` to selectively include at compile time the calls to initialise the selected serial port and send stdio text to the selected Serial driver.

Notes: 
- This PR does not change or use ```HalSystemConfig.stdio``` defined within nanoFramework. That will need a more extensive review and much wider scope of work to follow at some point.
- Although it is possible to select a different UART in cmake-variants.json, the board.h is currently hard coded to enable UART4 alternate functions as the call ```sdStart(&SERIAL_DRIVER_STDIO, NULL)``` is not configuring the UART GPIO pins. Ideally the GPIO would be setup dynamically when the port is initialised and then the standard board.h may be used. 
- The baudrate, stop bits, parity will use the "default" values as used by WP UART. Is there a need to pick something different?
-  This PR includes a conditionally compiled call to ```CLR_Debug::Printf("CLR_DBG_Debugger::Monitor_Ping...\r\n");``` when incoming ping requests arrive as an example. (Not included in RTM builds. Not included if NF_FEATURE_TRACE_TO_STDIO is not defined.)
- Current linker settings in ST_B_L475E_IOT01A Azure build limits bootloader to 26K. If any ```NF_WP_TRACE_xx``` are defined, then nanoBooter will exceed the space available by 400 to 600 bytes. 
- Do be aware that adding trace adds overhead. Even with text sent to UART via buffered interrupts can change speed of processing and execution timing, especially if extensive text sent to stdio or a slow baud rate used.

## Motivation and Context
When adding functionality to the Native code base it can be helpful to trace out state as software is executed without requiring breakpoints that stop code execution and require user intervention, which can be too slow if there are fast timeouts (e.g. USB, WP). 

## How Has This Been Tested?
Define ```"NF_FEATURE_TRACE_TO_STDIO": "4",```` build and deploy and confirm VS2019 can deploy nBlinky. Confirm removing the setting also compiles and deploys Ok. 

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New optional feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-14 23:30 UTC, doingnz commented
Please have a look at the way the code style checker has reformatted board.h. Is that what the project wants or should the board.h file be marked in some way that it is not processed by the style checker?

2021-09-15 06:57 UTC, josesimoes commented
> Please have a look at the way the code style checker has reformatted board.h. Is that what the project wants or should the board.h file be marked in some way that it is not processed by the style checker?

Agreed. That's not optimal, especially for diffs with the original files in ChibiOS sources.
I've been fixing this (when it manifests) by adding:

`// clang-format off` after the header

and 

`// clang-format on` at the end of the file.

Can you please do that for this one and revert the style changes?

2021-09-15 11:43 UTC, doingnz commented
I can add the ```// clang-format off/on``` fixes formatting easily.

2021-09-15 11:48 UTC, doingnz commented
What are your thoughts on the changes to GPIO definitions in this file to enable UART4?

e.g. to use UART4 with SD4 driver needs the GPIO defined in board.h as follows

```
#define VAL_GPIOA_AFRL              (PIN_AFIO_AF(GPIOA_USART4_TX, 8U) |    \
                                     PIN_AFIO_AF(GPIOA_USART4_RX, 8U) |    \
```

the default values in the original board.h were
```
#define VAL_GPIOA_AFRL              (PIN_AFIO_AF(GPIOA_JOY_CENTER, 0U) |    \
                                     PIN_AFIO_AF(GPIOA_JOY_LEFT, 0U) |      \
```


The problem from my perspective is I don't see where in the firmware the state of these GPIO would be set differently when we call sdInit(&SD4). I am missing something that is probably obvious to you :-)
```

2021-09-15 11:56 UTC, josesimoes commented
> What are your thoughts on the changes to GPIO definitions in this file to enable UART4?

Those ones to change the AF are OK, but you need to make sure the other configs for those pins are correct too. Just follow one of the other UARTs there.

As for these GPIO configs: they are applied as the default on boot. So if you have the UART4 GPIOs fully configured here, you're good to go on "just" calling sdInit(&SD4). (still need to enable on mcuconf.h, of course)

2021-09-15 12:02 UTC, doingnz commented
yes it is good to go when board.h is configured... but that implies a fixed configuration using UART4 (which is OK for what I am doing). I am just asking as we have lost the flexibility that  
```
"NF_FEATURE_TRACE_TO_STDIO": "4",
```` 
permits the config to be ANY spare SD/UART ... if only the GPIO were set at runtime by each UART during init.

I am happy to leave it fixed to use UART4 for now and we can come back to this in the future...

2021-09-16 00:33 UTC, josesimoes requested changes
@doingnz I believe I've covered all the changes in the comments below.
If anything is not clear or not making sense, just let me know. 😃

2021-09-16 00:33 UTC, josesimoes commented on targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
> +//#define STM32_SERIAL_USE_UART4              FALSE
```suggestion
#define STM32_SERIAL_USE_UART4              TRUE
```

2021-09-16 00:33 UTC, josesimoes commented on targets/AzureRTOS/_common/StdioPort.cpp
> +#if defined(FEATURE_TRACE_TO_STDIO)
No need for this #define here. The file will be added to the build only if the build option it's ON.

2021-09-16 00:33 UTC, josesimoes commented on targets/AzureRTOS/_common/StdioPort.cpp
> +//
Please move this to ST\_common and rename to Target_GenericPort_stdio.c.

2021-09-16 00:33 UTC, josesimoes commented on targets/AzureRTOS/_common/CMakeLists.txt
> +if(NF_FEATURE_TRACE_TO_STDIO)
Please move this to the ST\_common\CMakeLists.txt

2021-09-16 00:33 UTC, josesimoes commented on targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
> +    // Don't init if Wifi Mode null (Disabled)
This doesn't seem to belong to this PR...

2021-09-16 00:33 UTC, josesimoes commented on targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcChannel.cpp
> +extern "C" uint8_t temprature_sens_read();
This doesn't belong to this PR, please remove.

2021-09-16 00:33 UTC, josesimoes commented on targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
> +// ADC2 with 10 channels (GPIO 0,2,4,12-15 and 25-27)
This doesn't belong to this PR, please remove.

2021-09-16 00:33 UTC, josesimoes commented on CMake/binutils.common.cmake
> +    # set compiler definition for implementing (or not) CRC32 in Wire Protocol
This doesn't belong here.
The correct place to expose this build option is to add it to the various NNNNN_target_os.h.in template inside the CMake folder. Like:
`#define TRACE_TO_STDIO       @NF_TRACE_TO_STDIO@`

2021-09-16 00:36 UTC, josesimoes commented on CMakeLists.txt
> +option(NF_FEATURE_TRACE_TO_STDIO "option to enable sending trace data to stdio. Requires spare SERIAL device")
Also make sure to add the new build option to .vscode\cmake-variants.TEMPLATE.json and the target's cmake-variants.json template.

2021-09-16 16:16 UTC, doingnz commented on targets/AzureRTOS/ST/ST_B_L475E_IOT01A/board.h
> +#define GPIOA_USART4_TX             0U
I reverted the entire file given we use the Configure_UART##num()... macro to setup the GPIO

2021-09-16 16:26 UTC, doingnz commented on src/CLR/Debugger/Debugger.cpp
> +#if !defined(BUILD_RTM) && defined(FEATURE_TRACE_TO_STDIO)
```TRACE_TO_STDIO``` or ```NF_TRACE_TO_STDIO```?

2021-09-16 16:47 UTC, doingnz commented on targets/AzureRTOS/ST/ST_B_L475E_IOT01A/common/serialcfg.h
> +//#define SERIAL_DRIVER_STDIO SD##FEATURE_TRACE_TO_STDIO
Now set the specific UART and Serial Driver in ```targets\AzureRTOS\ST\ST_B_L475E_IOT01A\target_stdio_config.c```. 
```
#define STDIO_UART          4
#define STDIO_SERIAL_DRIVER SD4
```
User expected to set both. 
e.g. for UART2
```
#define STDIO_UART          2
#define STDIO_SERIAL_DRIVER SD2
```

It expects and checks for existence of a macro UART_CONFIG_PINS(n, GPIOx, GPIOx,  x , x, x). 
Idea is to add additional macros for the other U[S}ARTS available on the Target and then only need to change the two #defines to move to another UART depending how the developer wants to use available resources.

2021-09-16 16:56 UTC, doingnz commented on targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoBooter/mcuconf.h
> +#define STM32_NO_INIT        FALSE
fixed.

Note expects the ```STM32_SERIAL_USE_UARTn``` to be defined TRUE where n must match what is in:
```
#define STDIO_UART          n
#define STDIO_SERIAL_DRIVER SDn
```
in the file the ```target_stdio_config.c```

2021-09-16 16:58 UTC, doingnz commented on targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/mcuconf.h
> +//#define STM32_SERIAL_USE_UART4              FALSE
yes I have changed to 
```
#define STM32_SERIAL_USE_UART4              TRUE     // STDIO
```

2021-09-16 17:08 UTC, doingnz commented on targets/AzureRTOS/_common/StdioPort.cpp
> +#if defined(FEATURE_TRACE_TO_STDIO)
good point fixed

2021-09-16 17:14 UTC, doingnz commented on targets/AzureRTOS/_common/StdioPort.cpp
> +//
functionality is now in targets\AzureRTOS\ST\ST_B_L475E_IOT01A\target_stdio_config.c.

I did consider putting the "write" in it's own file at the "ST" level, but then thought it was simpler to keep the "Init" and "Write" together in a single file as they are tightly coupled. Public interface is the two methods: 
```
void StdioPort_Init(); 
uint32_t StdioPort_Write(int portNum, const char *data, size_t size)
```

Which don't have any info that is target specific. portNum is ignored for now till the wider questions around trace vs WP output are resolved.

2021-09-16 17:14 UTC, doingnz commented on targets/FreeRTOS_ESP32/ESP32_WROOM_32/Network/Esp32_Wireless.cpp
> +    // Don't init if Wifi Mode null (Disabled)
removed accidental merge of develop branch

2021-09-16 17:15 UTC, doingnz commented on targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcChannel.cpp
> +extern "C" uint8_t temprature_sens_read();
removed accidental merge of develop branch

2021-09-16 17:15 UTC, doingnz commented on targets/FreeRTOS_ESP32/ESP32_WROOM_32/nanoCLR/Windows.Devices.Adc/win_dev_adc_native_Windows_Devices_Adc_AdcController.cpp
> +// ADC2 with 10 channels (GPIO 0,2,4,12-15 and 25-27)
removed accidental merge of develop branch

2021-09-16 17:16 UTC, doingnz commented on targets/AzureRTOS/_common/CMakeLists.txt
> +if(NF_FEATURE_TRACE_TO_STDIO)
done

2021-09-16 17:38 UTC, doingnz commented on CMake/binutils.common.cmake
> +    # set compiler definition for implementing (or not) CRC32 in Wire Protocol
implemented #define TRACE_TO_STDIO @NF_TRACE_TO_STDIO@ and renamed define in c/c++/h to TRACE_TO_STDIO

2021-09-16 17:41 UTC, doingnz commented on src/CLR/Debugger/Debugger.cpp
> +#if !defined(BUILD_RTM) && defined(FEATURE_TRACE_TO_STDIO)
see below, implemented as TRACE_TO_STDIO in c/c++/h files
NF_TRACE_TO_STDIO in cmake/build files.

2021-09-17 01:43 UTC, doingnz commented on CMake/binutils.common.cmake
> +    # set compiler definition for implementing (or not) CRC32 in Wire Protocol
I have updated the branch to use this mechanism and add line to AzureRTOS os.h.in file.  
```
#define TRACE_TO_STDIO @NF_TRACE_TO_STDIO@
```

It will be necessary to edit ALL  NNNNN_target_os.h.in to have this definition as TRACE_TO_STDIO is used in src/CLR/Debugger/Debugger.cpp and will be in other src/CLR/... files over time.

I think it is better to revert this change and define TRACE_TO_STDIO in the CMake files as it is then possible to define it to a default FALSE (or undefined).

As a workaround to get the build to pass, I have inserted 
```
#if !defined(TRACE_TO_STDIO)
#define TRACE_TO_STDIO FALSE
#endif
```
into the top of Debugger.cpp

Which suggests another approach is to add these lines to a file like hal.h or nanoHAL.h if you prefer to continue with the #define in the os.h.in file and not move this setting back into the CMake files. 

Please let me know how you wish to close this out.

This is a thin edge of a wedge as there are wider questions to be answered about unification of "TRACE" type statements in the code base as a few different approaches scattered through nF and target src.

2021-09-17 11:44 UTC, doingnz commented on CMake/binutils.common.cmake
> +    # set compiler definition for implementing (or not) CRC32 in Wire Protocol
I changed this line
```
#if !defined(BUILD_RTM) && (TRACE_TO_STDIO == TRUE)
``` 
to include defined(TRACE_TO_STDIO) 
```
#if !defined(BUILD_RTM) && defined(TRACE_TO_STDIO) && (TRACE_TO_STDIO == TRUE)
```
and removed the 
```
#if !defined(TRACE_TO_STDIO)
#define TRACE_TO_STDIO FALSE
#endif
```

2021-09-17 15:25 UTC, josesimoes requested changes
Just that last tiny bit and it's good for merging 😉

2021-09-17 15:25 UTC, josesimoes commented on targets/AzureRTOS/ST/ST_B_L475E_IOT01A/CMakeLists.txt
> +if(TRACE_TO_STDIO)
This is now @ targets/AzureRTOS/ST/_common/CMakeLists.txt (which is broader) so it can be removed from here.

2021-09-17 17:29 UTC, josesimoes approved these changes
All good now!! Thanks for this fine new feature. 💯

2021-09-17 17:42 UTC, merged