Add SPI support to AzureRTOS on ST_B_L475EIOT01A
nanoframework/nf-interpreter pull request #2048
Opened 2021-09-18 15:24 UTC by doingnz

## Description
Define target files and provide brief description of what is attached to the different SPI devices on on the target STM32L475. 
```
targets\AzureRTOS\ST\ST_B_L475E_IOT01A\target_system_device_spi_config.cpp
targets\AzureRTOS\ST\ST_B_L475E_IOT01A\target_windows_devices_spi_config.cpp 
```
Update definition of the number of SPI to 3 ```#define NUM_SPI_BUSES 3```
Add new section with limit values for STM32L4XX clocks for SPI.
Add clang off/onn and cleanup duplicated defines in targets/AzureRTOS/ST/ST_B_L475E_IOT01A/nanoCLR/halconf.h

## Motivation and Context
Part of migration of nanoFramework to run on AzureRTOS using ChibiOS HAL.

## How Has This Been Tested?
Confirm with logic analiser correct baudrate write ro SPI1 (on CN1) and SPI2 (on PMOD)

## Screenshots
![image](https://user-images.githubusercontent.com/5063598/133893858-8f8d53fd-da0f-4964-ad40-db68ce46a79e.png)

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-19 18:58 UTC, josesimoes requested changes

2021-09-19 18:58 UTC, josesimoes commented on targets/AzureRTOS/Maxim/_nanoCLR/target_platform.h.in
> +#define NANOCLR_GRAPHICS      @NANOCLR_GRAPHICS @
Please remove the extra space before the @, otherwise the template won't be correctly processed by CMake.

Better don't run the clang to the template files. It breaks things. 😉

2021-09-20 07:34 UTC, doingnz commented on targets/AzureRTOS/Maxim/_nanoCLR/target_platform.h.in
> +#define NANOCLR_GRAPHICS      @NANOCLR_GRAPHICS @
I have fixed it and I added clang-format off. Maybe there is a way to tell clang-format to always ignore .h.in files as I added the clang-format on file save to avoid PR that fail style check.

2021-09-20 07:38 UTC, josesimoes commented on targets/AzureRTOS/Maxim/_nanoCLR/target_platform.h.in
> +#define NANOCLR_GRAPHICS      @NANOCLR_GRAPHICS @
This shouldn't be needed. The clang filter in the pipeline it's picking the .h.in files so any changes here have to be made locally...

2021-09-20 07:39 UTC, josesimoes approved these changes
Well done!! 👍🏻

2021-09-20 07:45 UTC, merged