simpler top-level cmakelists.txt
nanoframework/nf-interpreter pull request #2083
Opened 2021-09-30 10:59 UTC by doingnz

## Description
Removed most of the custom RTOS & target logic as the approach encouraged additional script for each additional target. 
This PR does not change the logic for the two ESP targets other than to use the same named CMake variables for the RTOS and Target folders to show how close it is to being the same as the other targets. Given the ESP targets are being reworked for the update to 4.x, I have left that change to the person doing the ESP update to remove ESP difference.

## Motivation and Context
Ideally there would be no RTOS or TARGET specific logic in this top-level CMakeLists.txt to aim for reduced responsibility and remove chance of unexpected interactions when new platforms added. its purpose should be restricted to check a target exists and validate high level shared options common to all nanoFramework targets. It also manages the selection of the standard target or community target. 

With this change, a new ${RTOS} & ${TARGET} will be found simply by creation of the folders under /targets. i.e. /targets/${RTOS}/${TARGET}

## How Has This Been Tested?
Confirmed can build ESP32 and STM32 targets. 

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-09-30 12:06 UTC, josesimoes requested changes

2021-09-30 12:06 UTC, josesimoes commented on CMakeLists.txt
> +    message(STATUS "\nSetting RTOS to ${RTOS} Exists!\n")
```suggestion
    message(STATUS "\nSetting RTOS to ${RTOS}\n")
```

2021-09-30 12:06 UTC, josesimoes commented on CMakeLists.txt
> +if(RTOS_FREERTOS_CHECK)
I guess this should be:
```suggestion
if(RTOS_FREERTOS_ESP32_CHECK)
```

2021-09-30 19:26 UTC, doingnz commented on CMakeLists.txt
> +if(RTOS_FREERTOS_CHECK)
There are two platforms at the start of the "custom" platforms logic related to FreeRTOS. Please see a couple of lines below your suggested edit the if(RTOS_FREERTOS_ESP32_CHECK)

```
#######################
# FreeRTOS
if(RTOS_FREERTOS_CHECK)

    add_subdirectory(targets/FreeRTOS)

#######################
# FreeRTOS ESP32
elseif(RTOS_FREERTOS_ESP32_CHECK)
```

2021-09-30 20:31 UTC, josesimoes commented on CMakeLists.txt
> +if(RTOS_FREERTOS_CHECK)
If this is the IF for FREERTOS, then the code below doesn't belong here as it's validating RTC for ESP32, which would belong to _another_ IF....

2021-09-30 20:33 UTC, josesimoes commented on CMakeLists.txt
> +if(RTOS_FREERTOS_CHECK)
Forget my comment above. I was mislead by the partial representatiuon of the diff on git. After looking at the complete file, I can see the code block is correct.

2021-09-30 20:34 UTC, josesimoes approved these changes
LGTM!

2021-09-30 20:40 UTC, merged

2021-10-01 00:23 UTC, nightlark commented
@josesimoes I'm not sure how nfbot is deciding when to apply the `invalid` label, since it seems to be getting added to merged PRs and ones that have been closed and replaced by a newer PR. Given that hacktoberfest is apparently counting `invalid` labels towards disqualification, use of the label by nfbot should probably be paused until after October.

2021-10-01 07:51 UTC, josesimoes commented
> @josesimoes I'm not sure how nfbot is deciding when to apply the `invalid` label, since it seems to be getting added to merged PRs and ones that have been closed and replaced by a newer PR. Given that hacktoberfest is apparently counting `invalid` labels towards disqualification, use of the label by nfbot should probably be paused until after October.

@nightlark criteria for adding invalid label is for PRs that where closed without being merged. This one must have been a glitch resulting from the order the git events where processed. The code processing these hasn't been changed for months now. I've also randomly checked several other PRs and couldn't find any that was wrongly labeled. 
Thanks for sharing your concern! 😃 👍🏻