Fixes Ethernet support in latest builds
nanoframework/nf-interpreter pull request #2247
Opened 2022-02-06 05:04 UTC by AdrianSoundy

## Description

There was issues in the latest build not including the Ethernet support
- Ethernet option were incorrect
- ETHERNET_SUPPORT flag not being seen by other modules
- Connects not working as Wireless in enabled but not connected by default.
- DHCP issues when testing with sample Network Client

The only IDF config that supported Ethernet correctly was the sdkconfig.default used by LILYGO build. The binutils.ESP32.cmake looked for specific patterns in sdkconfig to update Ethernet configuration.

This Ethernet config has been updated to include option of SPI EThernet controllers in a build.
The changed sdkconfig ethernet section has been copied to all available IDF configs so all build type can have the option of Ethernet ( Internal or SPI )

The TCP connects not working was caused by having the Wireless interface enabled. To make this simpler for builds with Ethernet interface included it will now disable wireless on first start when config built and saved. 

The problems with DHCP were found to be caused by Network helper enabling DHCP at the same time DHCP was running in background. System.Net changed and updated to only Enable DHCP when not already enabled, which resolved problem.

As we now have option of supporting multiple PHY the NF_ESP32_Ethernet_Lan8720.cpp has been updated and renamed.  Support included for more internal PHY types and the options of SPI controllers like WIZ5500. 

These currently can only be enabled by changing options in esp32_ethernet_options.h.in but later we can enable it to be selected from build or dynamically from managed code. Out of scope for this PR.  

## Motivation and Context
Had project that used Ethernet but didn't work with latest builds
also
- Fixes nanoFramework/Home#951

## How Has This Been Tested?

An updated version of sample Network client used. Sample has also be updated with latest Network Helper.

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-07 11:51 UTC, josesimoes requested changes

2022-02-07 11:51 UTC, josesimoes commented on targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
> +#
I believe this sdkconfig wasn't meant to be in the PR... please confirm

2022-02-07 11:51 UTC, josesimoes commented on targets/ESP32/_IDF/sdkconfig.default_pico
> +CONFIG_ETH_ENABLED=y
Does it make sense to enable these for the PICO?

2022-02-07 11:51 UTC, josesimoes commented on targets/ESP32/_Network/esp32_ethernet_options.h.in
> +//#define ESP32_ETHERNET_PHY_IP101
I'm not very keen of this approach... this is a template file therefore it's not supposed to require any tweaks to build one target or the other. Not having to edit it to add/remove build options.

I get it that this is a convenient file to manage all these options. If that's the case, then let's expose the build options properly and map them properly. Let's follow up on Discord.

2022-02-07 12:02 UTC, AdrianSoundy commented on targets/ESP32/_IDF/sdkconfig.default_pico
> +CONFIG_ETH_ENABLED=y
I enabled the Ethernet drivers for all build types. It just means the driver will be available in Library if anybody enables it.  With the SPI controllers available that's likely to happen.  Having this option doesn't increase size of firmware just increases build time slightly.

2022-02-07 12:05 UTC, AdrianSoundy commented on targets/ESP32/_Network/esp32_ethernet_options.h.in
> +//#define ESP32_ETHERNET_PHY_IP101
This was only a temporary solution to allow testing until we add some proper build options. I wanted to handle that in separate PR.

2022-02-07 12:06 UTC, AdrianSoundy commented on targets/ESP32/_IDF/sdkconfig.debug_nopsram_ble.esp32
> +#
Currently the debug builds don't include debug symbols for debugging

2022-02-08 00:58 UTC, josesimoes commented on targets/ESP32/_Network/esp32_ethernet_options.h.in
> +//#define ESP32_ETHERNET_PHY_IP101
Understood. Let's have that in queue asap, so this doesn't be left hanging for too long.

2022-02-08 01:00 UTC, josesimoes approved these changes

2022-02-08 09:36 UTC, AdrianSoundy commented
Not sure why you removed Bug label.  The Ethernet support is currently broken.

2022-02-08 09:55 UTC, merged

2022-02-08 10:10 UTC, josesimoes commented
> Not sure why you removed Bug label. The Ethernet support is currently broken.

Because the root cause was in the build system. Not exactly in the code. 
OK there where changes required in the code, but still... 😁