Added DrawChar method to Bitmap
nanoframework/nf-interpreter pull request #2390
Opened 2022-06-30 18:49 UTC by mikeoliphant

## Description
This change adds a DrawChar method to the managed Bitmap class.

## Motivation and Context
Previously, the only way to draw a single character was to draw a single-character string. This has a fair bit of extra overhead. The new DrawChar() method does this more efficiently.

## How Has This Been Tested?
Tested locally on M5Stack Core2.

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

2022-06-30 18:51 UTC, mikeoliphant commented
Corresponding nanoFramework.Graphics PR is here: https://github.com/nanoframework/nanoFramework.Graphics/pull/107

2022-07-01 14:05 UTC, Ellerbach commented on src/nanoFramework.Graphics/Graphics/Core/Graphics.h
> +
please use explicit brackets, we're moving to have them in native as well.

2022-07-01 14:07 UTC, Ellerbach commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_Bitmap.cpp
> +        pArgs[0].NumericByRef().u2,
are you sure you have 4 arguments? From the definition, seems only 3

2022-07-01 14:23 UTC, mikeoliphant commented on src/nanoFramework.Graphics/Graphics/Core/Graphics.h
> +
Fixing now.

2022-07-04 22:43 UTC, josesimoes requested changes
Just the version needs to be bumped. All ood for the rest. 👍

2022-07-04 22:43 UTC, josesimoes commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
>      { 100, 0, 0, 4 }
Change in API calls for bumping the native assembly version too. Please do this here and on the C# lib too.

2022-07-06 01:01 UTC, mikeoliphant commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics.cpp
>      { 100, 0, 0, 4 }
Done.

2022-07-06 01:47 UTC, josesimoes approved these changes
LGTM!

2022-07-06 02:05 UTC, merged