ILI9341 display driver update
nanoframework/nf-interpreter pull request #2411
Opened 2022-08-17 14:24 UTC by lsd-techno

## Description

- Update display driver and features for ILI9341 display support
- Support smaller physical resolution than 240x320
- Enabled display orientation switch function
- Fixes some parameters related to logic screen size

## Motivation and Context

- Improve display support

## How Has This Been Tested?

## Screenshots

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

2022-08-17 14:44 UTC, Ellerbach reviewed
My main question is related to this new driver. How different form the 240x320? And is there maybe a better way to have just 1 single file if there are few differences?

2022-08-17 14:44 UTC, Ellerbach commented on targets/ESP32/CMakeLists.txt
> +set(ESP32_IDF_TAG "4.4.2" CACHE INTERNAL "ESP32 IDF tag")
why is this needed? You haven't touch the dev container at all

2022-08-17 14:44 UTC, Ellerbach commented on src/nanoFramework.Graphics/Graphics/Displays/ILI9341_XXXxYYY_SPI.cpp
> +//
how different is this driver compare to the 240x320?

2022-08-17 15:29 UTC, lsd-techno commented on src/nanoFramework.Graphics/Graphics/Displays/ILI9341_XXXxYYY_SPI.cpp
> +//
Description add

2022-08-17 15:36 UTC, lsd-techno commented on targets/ESP32/CMakeLists.txt
> +set(ESP32_IDF_TAG "4.4.2" CACHE INTERNAL "ESP32 IDF tag")
Temporary revert IDF version back to 4.4.1 (untill container get updated)

2022-08-17 16:16 UTC, lsd-techno commented on src/nanoFramework.Graphics/Graphics/Displays/ILI9341_XXXxYYY_SPI.cpp
> +//
This version is functional compare to previous.
I think we will replace old versions with this one.
1. Current version made with thinking on possible different hardware resolution (less than 240x320).
2. It has more universal initialization (rely on display manufacturer for the moment to not damage display module).
3. possible I can move it to universal ILI9xxx support

2022-08-18 09:08 UTC, josesimoes requested changes
We're not pulling in sub-modules from IDF. 
Please remove components/coap/libcoap.

2022-08-18 09:17 UTC, josesimoes commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
> +                        posY += heightChar; // add max character height of current line
Code style call for comments before the code line/block. Please follow.

2022-08-18 09:17 UTC, josesimoes commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
> +    stack.SetResult_Boolean(g_GraphicsDriver.ChangeOrientation((DisplayOrientation)orientation));
This is probably fixing a bug with the SetResult_Boolean not being called. 
Please make this a separate PR because its not related with the new ILI9341 driver.

2022-08-18 09:17 UTC, josesimoes commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
> +        // GFX_Pen pen;
All the code modifications here seem to be changing the `Write___STATIC__VOID__STRING__U2__U2__U2__U2__nanoFrameworkUIFont__nanoFrameworkPresentationMediaColor__nanoFrameworkPresentationMediaColor`  behavior. 🤔 

This function is used in generic UI DisplayControl. A couple of thoughts:
- If this is fixing/improving something on the generic behavior then it belongs to a separate PR.
- If it's required specifically for the new ILI9341 driver, then it needs to be validated with other displays as well.

2022-08-19 13:13 UTC, merged

2022-08-19 22:19 UTC, lsd-techno commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
> +                        posY += heightChar; // add max character height of current line
Changes isolated from display driver update.

2022-08-19 22:19 UTC, lsd-techno commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
> +    stack.SetResult_Boolean(g_GraphicsDriver.ChangeOrientation((DisplayOrientation)orientation));
Changes isolated from display driver update.

2022-08-19 22:19 UTC, lsd-techno commented on src/nanoFramework.Graphics/Graphics/Native/nanoFramework_Graphics_nanoFramework_UI_DisplayControl.cpp
> +        // GFX_Pen pen;
Changes isolated from display driver update.

2022-08-19 22:27 UTC, lsd-techno commented
seems I have to make new PR as this one seems stuck after force merging