Add build option to reserve internal RAM for IDF allocation
nanoframework/nf-interpreter pull request #2460
Opened 2022-11-01 12:50 UTC by josesimoes

## Description
- Add CMake build option `ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION`.
- Update CMake and ESP32 target platform accordingly.
- Update memory allocation define.
- Update CmakePresets for all PICO and Ethernet targets to reserve 10k of internal RAM.

## Motivation and Context
- Exposes option to reserve RAM for IDF allocation.
- This has come up in the review of PR #2456 which was fixing nanoframework/Home#1166.

## How Has This Been Tested?

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [x] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

2022-11-02 03:16 UTC, AdrianSoundy requested changes

2022-11-02 03:16 UTC, AdrianSoundy commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
Rev3 and bluetooth so no required.

2022-11-02 03:16 UTC, AdrianSoundy commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
Config without psram so not required

2022-11-02 03:16 UTC, AdrianSoundy commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
This device is a pico D4 without psram but this entry is using a normal esp32 nopsram config which seems wrong. If right then doesn't need the ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION

2022-11-02 03:34 UTC, AdrianSoundy commented
The builds are failing because its not finding the default value of ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION (0)
So we get 
```
C:/nanof/nf-interpreter/build/targets/ESP32/ESP32/target_platform.h:13:47: error: 'OFF' was not declared in this scope
[build]  #define ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION OFF
```

2022-11-02 10:05 UTC, josesimoes commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
You are correct. Let's fix this on another PR.
Regarding this one: as this is a PICO without PSRAM it should have these reserved 10k, correct?

2022-11-02 10:05 UTC, josesimoes commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
I was under the impression that these extra 10k where required for devices WITHOUT PSRAM, that's why I've added it here...

2022-11-06 00:17 UTC, AdrianSoundy commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
It's for  Rev 1 devices that have psram configured which uses over 10K of ram for the psram fixes library.
So really for rev 1 devices which have psram configured only. Like the PICO which had the psram enabled causing the problem.

2022-11-06 00:18 UTC, AdrianSoundy commented on CMakePresets.json
> +                "ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION": "10",
Shouldn't need extra ram as current config without psram.

2022-11-06 00:19 UTC, AdrianSoundy commented
Other than changes above looks good to me,

2022-11-07 11:06 UTC, merged