Updates for Pairing security and authentication
nanoframework/nf-interpreter pull request #2584
Opened 2023-02-26 23:23 UTC by AdrianSoundy

## Description

- Adds support for Pairing for Client and Server applications
- Updates to support latest nanoFramework.Device.Bluetooth
- Fixes to stability/exceptions when stopping and starting Bluetooth stack

Known problem

There is a small native memory leak when stopping and starting Client application. Only an issue when continuously starting and stopping. This will be handled in later PR. 

## Motivation and Context
Add support for Pairing

## How Has This Been Tested?

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

2023-02-28 00:39 UTC, alberk8 requested changes

2023-02-28 00:39 UTC, alberk8 commented on targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
> +    size_t nlen = hal_strlen_s(bleDeviceName);
Free the Memory allocation.  This fixes the small memory leak.   Otherwise the rest looks good.

```
if(bleContext.pDeviceName)
{
     platform_free((void *)bleContext.pDeviceName);
}
```

2023-02-28 00:45 UTC, AdrianSoundy commented on targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
> +    size_t nlen = hal_strlen_s(bleDeviceName);
thanks for looking into that. didn't have anymore time before holiday. have to rerun test and make sure that fixes proble.

2023-02-28 01:14 UTC, alberk8 commented on targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
> +    size_t nlen = hal_strlen_s(bleDeviceName);
I have been testing it for a few hours and there is no leak detected.

2023-02-28 09:38 UTC, AdrianSoundy commented on targets/ESP32/_nanoCLR/nanoFramework.Device.Bluetooth/sys_dev_ble_native_nanoFramework_Device_Bluetooth_BluetoothNanoDevice.cpp
> +    size_t nlen = hal_strlen_s(bleDeviceName);
Should be resolved in latest change. Also added a missing FreeContext in stop advertising.
Seems to fix problem with my limited testing

2023-02-28 09:39 UTC, AdrianSoundy commented
Will need to work on nanoFramework.devcie.Bluetooth before this can be merged

2023-03-08 08:38 UTC, AdrianSoundy commented
@josesimoes 
Any idea why the code style checks seem to be broken.
No style errors in logs just seems to be a problem submitting  PR.

2023-03-08 10:26 UTC, josesimoes commented
@AdrianSoundy looking into this now

2023-03-08 12:20 UTC, josesimoes commented
@AdrianSoundy issue in pipeline fixed.

2023-03-09 04:45 UTC, AdrianSoundy commented
@josesimoes 
Thanks

2023-03-09 05:20 UTC, AdrianSoundy commented
@Ellerbach @alberk8 
All changes from reviews have now been completed for here and Bluetooth assembly. Tested Client & server with samples Central3 and Bluetoothsample2.  Just need an approving review and it can be merged.

Once done i will update  samples with new nuget.

2023-03-09 05:23 UTC, alberk8 commented
> @Ellerbach @alberk8 All changes from reviews have now been completed for here and Bluetooth assembly. Tested Client & server with samples Central3 and Bluetoothsample2. Just need an approving review and it can be merged.
> 
> Once done i will update samples with new nuget.

I have given the approval.  :)

2023-03-09 05:23 UTC, alberk8 approved these changes

2023-03-09 20:09 UTC, merged