Fix ESP32 C3 out of nanoFramework Memory
nanoframework/nf-interpreter pull request #2927
Opened 2024-05-12 08:18 UTC by alberk8

## Description

C3 firmware cannot run beyond simple Hello world.

## Motivation and Context

The problem arise in the way the IDF 5.x calculate the available memory vs IDF 4.4.

## How Has This Been Tested?

Tested on ESP32 C3 with and without BLE.
Tested on ESP32S3 with OCT PSRAM
Tested on ESP32 REV0 and REV3

## Screenshots

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

2024-05-14 04:29 UTC, AdrianSoundy commented
This parameter is only relevant to devices without PSRAM as all remaining PSRAM goes to the managed heap.

Tests with ESP32_C3 (PSRAM not available)
When it starts it has 114K of ram available for allocation. The 100K for IDF allocations is too big and changing to 50 should give room for a TLS or BLE application.  50K for IDF gives about 62K for managed heap instead of 12K.

2024-05-14 04:36 UTC, AdrianSoundy requested changes
Changes to CMakePresets.json look good to me. Just remove change for memory.cpp as not required.

2024-05-14 04:36 UTC, AdrianSoundy commented on targets/ESP32/_nanoCLR/Memory.cpp
> +        size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
Don't see any need to change this. It just looking for max free space in SPIRAM.

2024-05-14 06:16 UTC, alberk8 commented on targets/ESP32/_nanoCLR/Memory.cpp
> +        size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
The issue is that with `heap_caps_get_largest_free_block(memoryCaps | MALLOC_CAP_SPIRAM);` it will return the 8bit internal RAM and/or PSRAM depending if PSRAM is present.   

With `heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM); `  it is a surefire way to detect if there is PSRAM or NOT.

2024-05-15 00:55 UTC, AdrianSoundy commented on targets/ESP32/_nanoCLR/Memory.cpp
> +        size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
Did you actually test this. As my tests show the current code returns 0 for this statement so doesn't include internal memory. The memoryCaps only indicates that the memory has to be capable of 8bit and 16bit access.
Also don't want to have to test other targets which change would possibly affect.

2024-05-15 01:22 UTC, AdrianSoundy commented
These are the memory details from C# 
 Before: (Managed heap is 12288)
 Managed:3192 Native total:271712/Free:162572/Largest:114688
 
 After: (Managed heap is 63488)
 Managed:54396 Native total:271712/Free:111364/Largest:90112
 
 You could probably reduce the ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION even further to 30 which should allow enough for secure connections

2024-05-15 02:14 UTC, alberk8 commented on targets/ESP32/_nanoCLR/Memory.cpp
> +        size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
I just tested with the following ESP32 by adding the printf below.   It did show the correct values.

```
 size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
 ets_printf("SPIRAM Size: %d \n", spiramMaxSize);
```
**The Result** 
ESP32 with PSRAM
SPIRAM Size: 4128768

ESP32 S3 with PSRAM
SPIRAM Size: 8257536

ESP C3
SPIRAM Size: 0

2024-05-15 02:21 UTC, alberk8 commented
> These are the memory details from C# Before: (Managed heap is 12288) Managed:3192 Native total:271712/Free:162572/Largest:114688
> 
> After: (Managed heap is 63488) Managed:54396 Native total:271712/Free:111364/Largest:90112
> 
> You could probably reduce the ESP32_RESERVED_RAM_FOR_IDF_ALLOCATION even further to 30 which should allow enough for secure connections

One thing that I see in C3 is the the Native report Free is inaccurate.  Somehow it does not exclude the RAM taken by nF.

2024-05-15 11:11 UTC, AdrianSoundy commented
Memory report looks ok to me. Free memory is going down by about 50K.  The largest you can't judge as it could be a completely different heap block being reported.

2024-05-15 11:22 UTC, AdrianSoundy commented on targets/ESP32/_nanoCLR/Memory.cpp
> +        size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
The tests you are doing above report the same values as we get now with current code. The change doesn't fix anything.
Probably both ways work.  Just didn't want to change something that isn't broken.

Also later in code we do a heap_caps_malloc with the same "memorycaps" specification.  Just keeps is consistent how it is.

2024-05-16 00:29 UTC, alberk8 commented on targets/ESP32/_nanoCLR/Memory.cpp
> +        size_t spiramMaxSize = heap_caps_get_largest_free_block(MALLOC_CAP_SPIRAM);
Revert change.

2024-05-16 04:33 UTC, AdrianSoundy approved these changes
Looks good

2024-05-16 06:41 UTC, merged